namespace TRGE.Core.Item.Enums
{
    public enum TRItems
    {
        Pistols,
        Shotgun,
        AutoPistols,
        Uzis,
        HarpoonGun,
        M16,
        GrenadeLauncher,
        PistolClips,
        ShotgunShells,
        AutoClips,
        UziClips,
        Harpoons,
        M16Clips,
        Grenades,
        Flare,
        SmallMedi,
        LargeMedi,
        Pickup1,
        Pickup2,
        Puzzle1,
        Puzzle2,
        Puzzle3,
        Puzzle4,
        Key1,
        Key2,
        Key3,
        Key4
    }
}