using TRGE.Core.Item.Enums;

namespace TRGE.Core.Item;

public static class TRXNaming
{
    public static string GetName(TR1Items type)
        => _tr1Names[(int)type];

    public static TR1Items GetTR1Type(string name)
        => _tr1ReverseMap.TryGetValue(name, out var type) ? (TR1Items)type : TR1Items.Unknown;

    private static readonly Dictionary<int, string> _tr1Names = new()
    {
        [0] = "lara",
        [1] = "lara_pistols",
        [2] = "lara_shotgun",
        [3] = "lara_magnums",
        [4] = "lara_uzis",
        [5] = "lara_extra",
        [6] = "bacon_lara",
        [7] = "wolf",
        [8] = "bear",
        [9] = "bat",
        [10] = "crocodile",
        [11] = "alligator",
        [12] = "lion",
        [13] = "lioness",
        [14] = "puma",
        [15] = "ape",
        [16] = "rat",
        [17] = "vole",
        [18] = "trex",
        [19] = "raptor",
        [20] = "mutant_1",
        [21] = "mutant_2",
        [22] = "mutant_3",
        [23] = "centaur",
        [24] = "mummy",
        [25] = "dino_mutant",
        [26] = "fish_mutant",
        [27] = "larson",
        [28] = "pierre",
        [29] = "skateboard",
        [30] = "skate_kid",
        [31] = "cowboy",
        [32] = "baldy",
        [33] = "natla",
        [34] = "torso",
        [35] = "falling_block_1",
        [36] = "pendulum_1",
        [37] = "spikes",
        [38] = "rolling_ball_1",
        [39] = "dart",
        [40] = "dart_emitter",
        [41] = "drawbridge",
        [42] = "teeth_trap",
        [43] = "damocles_sword",
        [44] = "thors_handle",
        [45] = "thors_head",
        [46] = "lightning_emitter",
        [47] = "moving_bar",
        [48] = "movable_block_1",
        [49] = "movable_block_2",
        [50] = "movable_block_3",
        [51] = "movable_block_4",
        [52] = "sliding_pillar",
        [53] = "falling_ceiling_1",
        [54] = "falling_ceiling_2",
        [55] = "switch_type_normal",
        [56] = "switch_type_uw",
        [57] = "door_1",
        [58] = "door_2",
        [59] = "door_3",
        [60] = "door_4",
        [61] = "door_5",
        [62] = "door_6",
        [63] = "door_7",
        [64] = "door_8",
        [65] = "trapdoor_1",
        [66] = "trapdoor_2",
        [67] = "trapdoor_3",
        [68] = "bridge_flat",
        [69] = "bridge_tilt_1",
        [70] = "bridge_tilt_2",
        [71] = "passport",
        [72] = "compass",
        [73] = "photo",
        [74] = "cog_1",
        [75] = "cog_2",
        [76] = "cog_3",
        [77] = "player_1",
        [78] = "player_2",
        [79] = "player_3",
        [80] = "player_4",
        [82] = "gameplay",
        [83] = "save_crystal",
        [84] = "pistols",
        [85] = "shotgun",
        [86] = "magnums",
        [87] = "uzis",
        [88] = "pistol_ammo",
        [89] = "shotgun_ammo",
        [90] = "magnums_ammo",
        [91] = "uzis_ammo",
        [92] = "grenade",
        [93] = "small_medipack",
        [94] = "large_medipack",
        [95] = "graphics",
        [96] = "sound",
        [97] = "controls",
        [98] = "gamma",
        [110] = "puzzle_1",
        [111] = "puzzle_2",
        [112] = "puzzle_3",
        [113] = "puzzle_4",
        [118] = "puzzle_hole_1",
        [119] = "puzzle_hole_2",
        [120] = "puzzle_hole_3",
        [121] = "puzzle_hole_4",
        [122] = "puzzle_done_1",
        [123] = "puzzle_done_2",
        [124] = "puzzle_done_3",
        [125] = "puzzle_done_4",
        [126] = "lead_bar",
        [128] = "midas_touch",
        [129] = "key_1",
        [130] = "key_2",
        [131] = "key_3",
        [132] = "key_4",
        [137] = "key_hole_1",
        [138] = "key_hole_2",
        [139] = "key_hole_3",
        [140] = "key_hole_4",
        [141] = "pickup_1",
        [142] = "pickup_2",
        [143] = "scion",
        [147] = "scion_holder",
        [151] = "explosion_1",
        [152] = "explosion_2",
        [153] = "splash_1",
        [154] = "splash_2",
        [155] = "bubble_1",
        [156] = "bubble_2",
        [157] = "bubble_emitter",
        [158] = "blood_1",
        [159] = "blood_2",
        [160] = "dart_effect",
        [161] = "statue",
        [162] = "portacabin",
        [163] = "pods",
        [164] = "ricochet",
        [165] = "twinkle",
        [166] = "gun_flash",
        [167] = "dust",
        [168] = "body_part",
        [169] = "camera_target",
        [170] = "waterfall",
        [171] = "missile_1",
        [172] = "missile_2",
        [173] = "missile_3",
        [174] = "missile_4",
        [175] = "missile_5",
        [176] = "ember",
        [177] = "ember_emitter",
        [178] = "flame",
        [179] = "flame_emitter",
        [180] = "lava_wedge",
        [181] = "big_pod",
        [182] = "boat",
        [183] = "earthquake",
        [184] = "skybox",
        [185] = "pickup_aid",
        [186] = "temp_7",
        [187] = "temp_8",
        [188] = "temp_9",
        [189] = "lara_hair",
        [190] = "alphabet",
    };

    private static readonly Dictionary<string, int> _tr1ReverseMap = new();

    static TRXNaming()
    {
        foreach (var (id, name) in _tr1Names)
        {
            _tr1ReverseMap[name] = id;
        }
    }
}
